### ISSUE TITLE
Request permission workflow

### ISSUE THREAD

**Issue by SamMousa** [HeRAMS-WHO/herams-backend#349]
- [ ] Access requests can be done on Workspaces & Projects
- [ ] Access request include a subject and the type of access requested
- [ ] Users who can grant the requested access will see a list of all open requests and will be able to grant them
- [ ] Users who can grant the requested access will see a list of open requests for their favorite projects & workspaces
- [ ] Users who can grant the requested access will receive notifications of new requests for their favorite projects & workspaces
- [ ] Requests will expire after 2 weeks to prevent unattended requests stacking up
- [ ] When a request is granted a user will receive a notification
- [ ] When a new permission is granted outside of the request workflow it will be checked against outstanding requests and notify users of any indirectly fulfilled requests. (For example I requested access to Workspace X and have been granted access to the Project, it would fulfill the request)

**Comment by SamuelPetragallo** [comment]
I feel it needs to be more "traceable" for users requesting access (which also means more accountability to those granting access), maybe by:
1. ensuring it is visible who their request has gone to
2. not having requests expire after 2 weeks 

Maybe some other ideas there - ?

**Comment by SamMousa** [comment]
Not having them expire is a bad idea because it means sooner or later it will clutter up the system.
Doing 1 is a privacy issue. When requesting access you do not want to let that person know all users that might be able to answer these requests.

I think we should go with this first and improve later if it turns out not to work.

**Comment by SamuelPetragallo** [comment]
Ok let's go as is. Think traceability may become a thing though just as a headsup

**Comment by joester89** [comment]
Only the "Lead" gets the notifications #806

**Comment by joester89** [comment]
Questions @luna404 @SamMousa @SamuelPetragallo :
- Do we still need a subject and type? I believe we just discussed that you request access and just have a text box to describe what is needed.
- Do we still want the 2 weeks expiration?
- Where do we want the button to request access?
- Where do we want to show that there are outstanding requests for you to handle?
- Is the difference in requests for you in general or for your favorite projects still needed?

**Comment by luna404** [comment]
I've missed a part of the discussion this morning, so apologies if I contradict something that was agreed upon during the meeting.

- I think a subject line or title might still be useful. 
- Yes, but could we send a reminder per email to the "lead"? A lot of requests might go unanswered otherwise simply because users don't log in when they are not actively working on HeRAMs.
- I would say the same place we show who the focal point (same as #806)
- Taking into account we might have users which are admins for multiple projects, I think this should either be in a separate location or under the user profile. We could use something similar to GitHub to indicate new messages next to the user icon on top. .

**Comment by joester89** [comment]
More details from the discussion this morning:
- [ ] in the request we have a request title, body, checkboxes for permissions (read, write, download and other)
- [ ] store handled requests: who granted or denied when with a response message
- [ ] the read, write and download requests can be accepted implicetly (when permissions are granted outside of the access request flow)

**Comment by joester89** [comment]
@luna404 @SamuelPetragallo

This feature is available for testing now on https://feature-349-request-access.herams-staging.org.

**Data note**
This feature required database changes, meaning that the environment has a _new_ database with only very little data in it. You can log in with users: admin@user.com (admin), user@user.com (user) (will share password via chat). Since this feature requires testing of emails I recommend to create new accounts so the sent emails actually do end up in real mailboxes. These test accounts will be specific to this test environment.

**What has been implemented**
- At the location where project and workspace leads are shown, there now is link to request access, click it and you can request access.
- If an access request was created, the "closest leads" are notified of this. Closest means that for a workspace we first check if there are workspace leads, otherwise check if there are project leads. For a project we only check project leads. System admins are never notified except when marked as lead.
- Access requests expire after 2 weeks.
- When there are "open" access requests that you can respond to, you will see a notification icon in the top bar with a marker. Clicking it will go to the notifications page and show that there are open access requests for you to respond to.
- When responding to the access request, you can see which permissions were requested, can manually select the permissions that should be granted and must enter a response. Selecting no permissions will deny the request. When someone responds to the access request the requesting user will be notified.
- When an access request is granted (partially) this ia also handled and you will be notified. I.e. you request read and write access to a project, someone grants you read access by just adding you to the project, the access request will be marked as handled. You will be notified that it was granted partially.

**Comment by luna404** [comment]
Nice job, overall looks really good. Here are a few points I noticed while doing some initial testing. 

`When there are "open" access requests that you can respond to, you will see a notification icon in the top bar with a marker. Clicking it will go to the notifications page and show that there are open access requests for you to respond to.`
shouldn't this also be visible if I made a request and the request is pending approval? - Otherwise, why include the "outstanding access requests" in the notifications.
Also, the icon always shows 1 regardless of the number of open pending requests. 

`Access requests expire after 2 weeks.`
I know I said yes to this before, but I'm not sure it's actually a good idea. I think I would prefer if they don't expire. @SamuelPetragallo what do you think about this?
If an access request goes unanswered, is the requestor notified?

`If an access request was created, the "closest leads" are notified of this. Closest means that for a workspace we first check if there are workspace leads, otherwise check if there are project leads. For a project, we only check project leads. System admins are never notified except when marked as lead.`
This is not working as expected. I assigned a project lead to Chad but the request still goes to the global admin. I (the project admin) do not get the request.

On permissions, `update project` translates to a request for `edit settings`. Permission to edit project settings should not be available as a specific request. This should translate to `edit data`. To avoid confusion can we change the label for the requestor to show "contribute data"?

When requesting access to a workspace, I only have two options `update project` and `other`. Is this because there's no data for the workspace? I should have options to request access to `download` and `contribute data`. 


Some small things:
- breadcrumbs should be `Administration > Notifications
- I get a "content should be in section" error when writing a justification for granting/denying access. 
- I would remove the `favorites` column from the table. 
- For anyone else doing testing, the permissions for the test accounts are inverted. mixed. The `user` has admin privileges and vice versa.

**Comment by SamuelPetragallo** [comment]
Access requests expire after 2 weeks.

I also much prefer that these don't expire.
Reading through again the argument made was that not expiring would lead to cluttering the system. Not sure I get that though: I don't think we'd be hard deleting anything when expiring so is it very different?

The ideal scenario is that these are traceable and traced throughout their "lifecycle": if I've submitted a request I can see where it stands (and who it stands with) throughout. We want to avoid blackboxes which is how things currently work

**Comment by luna404** [comment]
Instead of removing answered requests, could we keep them in a separate table on the bottom of the page so a user can go back and see why/when a request was granted/rejected?

**Comment by joester89** [comment]
@luna404 @SamuelPetragallo there is a new version with the feedback processed on https://feature-349-request-access.herams-staging.org.

The admin and user logins are also correct now.

**Comment by luna404** [comment]
I can't do any testing until issue #849 has been resolved.

**Comment by joester89** [comment]
This is resolved now.

**Comment by luna404** [comment]
1. There is still an issue with the type of permissions a user can request.
<img src="https://user-images.githubusercontent.com/18245059/119818754-e1d18d00-beef-11eb-9a0e-dd634584adbb.png"  height="250">


- `View workspace` is definitely something we will need in the future, but with the current permissions, this cannot be granted. 
- `Update workspace` should not be an option to request. This should be lumped into "Other".
- Can we add the following options `Contribute data`  and `Other`. With the MHFL we will also need a separate option to request access to edit the MHFL. Not sure if we should already add this now or later. 

2. Content should be in section error
<img src="https://user-images.githubusercontent.com/18245059/119823353-00865280-bef5-11eb-98a3-d95ba367d8c3.png"  height="250">

3. This is a rather unlikely scenario, but a workspace owner can get an access request for permission they don't themselves have. Also, if a workspace owner is requesting access they're getting their own request for approval. 

4. If an access request is going to multiple people, it only stays in the history of the person who granted access. While this generally speaking makes a lot of sense, and avoids polluting the list of access requests for project admins, it also means access requests can "disappear" without an admin knowing whether it was granted or not or why it was only partially granted. @SamuelPetragallo what's your opinion on this? I'm leaning towards it would be better if anyone who received the request can see what was granted and it should therefore be added to the list of access requests a user responded to. Maybe this means we need to add a field showing who granted the request and change the header. 

5. What's the reasoning for having outstanding requests and granted requests in two different locations? It's nice to have the "alert" sign if you have outstanding requests but why not integrating them into the access request tab in the user profile as well?

**Comment by joester89** [comment]
@luna404, totally forgot to mention that the feedback was processed...

**Comment by LuciannaFG** [comment]
Hi all. I tested the "Request Access" and this error message appeared:

![image](https://user-images.githubusercontent.com/36709188/121859443-fdae9e80-ccf7-11eb-899c-e1e5102ba7cf.png)

**Comment by SamMousa** [comment]
Please always share the URL you are on when such errors occur.

**Comment by LuciannaFG** [comment]
Hi Sam, Noted! I'm still learning this "testing" part. So, I appreciate the directives. I believe you're talking about this URL: 

https://feature-349-request-access.herams-staging.org/session/create

I created an account "paratestar77@gmail.com"
Then, I requested access to a workspace in Nigeria - user name Luscianna Test
After I logged in as admi in HeRAMS using the URL above
And following this path: notifications -> Actions -> Actions, I got this error.

**Comment by SamMousa** [comment]
That's the login page. On the page where you get the error, copy the URL bar.

**Comment by LuciannaFG** [comment]
https://feature-349-request-access.herams-staging.org/access-request/3/respond

**Comment by SamMousa** [comment]
Great, with that I'm confident @joester89 will be able to figure out the actual issue ;-)

**Comment by luna404** [comment]
@joester89 it seems the error @LuciannaFG reported is caused by the users requesting "other" permissions.

**Comment by joester89** [comment]
@luna404 this now should be resolved.

**Comment by luna404** [comment]
Requesting `other` permissions is working, but I keep getting an error "You are not allowed to share this project" whenever I log in or submit a new access request.

**Comment by luna404** [comment]
I'm getting the below error on staging when submitting a new request:

`Setting unknown property: prime\models\ar\AccessRequest::expires_at`

**Comment by SamMousa** [comment]
@joester89 I think you forgot to commit a migration; you did apply it to the test database however.

**Comment by joester89** [comment]
@luna404 this now should work again on staging :)

**Comment by luna404** [comment]
I think @SamMousa hid the "request access" button when he did the release last week and it seems the button is still hidden on staging, could you check?

**Comment by luna404** [comment]
Still no button available to me :(
https://herams-staging.org/project/18/workspaces
![image](https://user-images.githubusercontent.com/18245059/128879743-4a661b00-9313-4e3a-a582-50bf4dfeea71.png)

**Comment by joester89** [comment]
![image](https://user-images.githubusercontent.com/9624366/128979541-562d802b-cb9e-4b3c-897b-ed727d393449.png)

It only shows when you do not already have admin access to a workspace. I logged in as the test user and then they do show up.

**Comment by luna404** [comment]
As a workspace/project owner I don't get an email when a new request was submitted that I need to act on. I only get the ones informing me that my access request was accepted/denied. Is this an error or was this changed on purpose?

**Comment by luna404** [comment]
I didn't realize you already implemented this in production. 

On my previous point, it seems only the workspace owner gets an email that there is a new access request. As we still don't have a workspace owner for the majority of workspace, for cases where the is no workspace owner, can we send the email to the project coordinator? 

Also, the last link in the emails is wrong. The 1 at the end needs to be removed
![image](https://user-images.githubusercontent.com/18245059/129225446-bb33080b-f1fe-4c12-9fef-6157fd7516fe.png)

**Comment by SamMousa** [comment]
@joester89 make sure you right a proper test that tests the link (takes it from the rendered email). Or at the very least make a ticket so it's on the Todo list.

**Comment by luna404** [comment]
@joester89 I thought access requests only go to workspace owners or project coordinators. I just did a demo with our new EMRO focal point and he could see and approve access requests for projects for which he had permissions at the project level despite not being listed as a project coordinator. Can we change this?

**Comment by SamMousa** [comment]
Seeing and approving is not the same as being notified. Project owner has all permissions a workspace owner does. Changing that behavior doesn't do anything for security.

**Comment by joester89** [comment]
We agreed upon the following flow:

*Seeing the requests*
All users that have the permission to `share` the resource that the access request is pointing to can see and respond to that access request, since these users can also grant users access which is basically the same. The permissions that a user can grant based on the access request is limited to the permissions that user has himself.

*Notifications of new access requests*
Only users that have the permission `lead` on a resource will be notified via email.

We can change that a project admin also gets notified of the new request, but with the current implementation that would also mean that that name will show up as workspace owner on all workspaces...

I'll look into the problem with the email and write a test for it.

**Comment by luna404** [comment]
Ok, my bad. I'll have to start paying better attention to what permission they're sharing on the project level. 

`We can change that a project admin also gets notified of the new request on a workspace, but with the current implementation that would also mean that that name will show up as workspace owner on all workspaces within that project...`
Would the name of the project owner disappear once a workspace owner was assigned?

**Comment by joester89** [comment]
> Would the name of the project owner disappear once a workspace owner was assigned?

In the current implementation not, if we want a `lead` of a project to be a `lead` on the workspace as well, then a added `lead` (aka workspace owner) would just be an extra name.

Thinking of a solution, @SamMousa, would it make sense to implement the leads just as a function (instead of the a bit ugly query approach) that returns users that have the permissions `ROLE_LEAD` on the workspace and if that is empty it checks the project? That would result in the scenario that @luna404 described.
