### ISSUE TITLE
Weblate base language for user guide is not updating

### ISSUE THREAD

**Issue by luna404** [HeRAMS-WHO/herams-backend#600]
The base language for the user guide in weblate does seem to updated anymore. 

It states that local repository is up to date, but when I compare it to the user guide itself, it doesn't show the latest version of the base language

https://weblate.herams-staging.org/projects/herams/herams-user-guide/#repository.

How can I force the base language to update?

**Comment by SamMousa** [comment]
I think this is resolved now.
Note that while looking at some texts, also the English ones, I saw things like `share Workspace`. As far as I know only the Germans capitalize every noun, the English definitely don't.

**Comment by luna404** [comment]
The text elements in weblate are still not up to date. See below for an example:

User guide:
![image](https://user-images.githubusercontent.com/18245059/94900003-91a34780-0494-11eb-8094-e4021d97599c.png)

https://docs.herams.org/fr/latest/#introduction

Weblate
![image](https://user-images.githubusercontent.com/18245059/94900050-9ff16380-0494-11eb-9ff8-b91e9d32fd65.png)
https://weblate.herams-staging.org/translate/herams/herams-user-guide/fr/?&offset=2

**Comment by SamMousa** [comment]
Ah, I get what you mean now.
The changes you make to `index.rst` in the repo are not resulting in regenerated PO files...

**Comment by SamMousa** [comment]
I have manually updated it now, you should be able to pull in weblate and see the new stuff.
Please confirm and I'll look into fixing the automated part

**Comment by luna404** [comment]
The changes still don't show correctly in weblate

**Comment by SamMousa** [comment]
Pff, finally found it!

We were missing some addon, enabling it caused WebLate to update the translation files with messages from the base file.

Please give it a go!

**Comment by luna404** [comment]
I confirm it did update all the string. But I'm not sure the issue is resolved. I did a small change to the base language this morning as a test and it seems to be the same issue. The new text is correct in user guide but it does not appear in weblate itself.

**Comment by luna404** [comment]
@SamMousa what do I have to after editing the .rst file in order for the base language in weblate to be updated? Changes I make are still not automatically reflected in weblate.

**Comment by SamMousa** [comment]
I have to look into the build process, essentially you have to run a sphinx command that extracts the strings from the rst file into the pot file.

I can not help with this today, so it will unfortunately have to wait unless you are able to figure it out yourself!

**Comment by SamMousa** [comment]
@luna404 I have recreated the automations required for this.

Any time a change is made to `index.rst` it will now automatically run the updates and push them back to this repo.
You can see that happening here: https://github.com/HeRAMS-WHO/herams-i18n/actions

The output of the job, shown here: https://github.com/HeRAMS-WHO/herams-i18n/actions/runs/378799394 lists several issues with the doc file that you should resolve.

When the platform is updated the same process happens. Since we are now using Github Actions both for updating the POT file from the `index.rst` content as well as updating individual PO files from the POT file, any future issues should be more easy to spot.

In Weblate I have removed the `msgmerge` addon, this is what was responsible for updating the PO file with the latest changes to the POT file.

**Comment by luna404** [comment]
I get an error in weblate after updating the `index.rst` file.

![image](https://user-images.githubusercontent.com/18245059/100114645-ed28fa80-2e71-11eb-87cc-81867baff8f7.png)

https://weblate.herams-staging.org/projects/herams/herams-user-guide/#alerts

**Comment by SamMousa** [comment]
Try now, it could be that some translations were lost...

**Comment by luna404** [comment]
Thanks, it's fine now. Is there anything I should do if this happens again?
